[context.production]
  [context.production.environment]
    REACT_APP_API_BASE_URL = "https://sirius-api.qa-dev.nyc3.k8s.warriorinvictus.com"
    REACT_APP_API_NAMESPACE = "v1"
    REACT_APP_VEHICLE_AUTOCOMPLETE_SEARCH = "true"

[context.deploy-preview.environment]
  REACT_APP_API_BASE_URL = "https://sirius-api.qa-dev.nyc3.k8s.warriorinvictus.com"
  REACT_APP_API_NAMESPACE = "v1"
  REACT_APP_VEHICLE_AUTOCOMPLETE_SEARCH = "true"

[context.branch-deploy]

[context.staging.environment]
