[context.production]
  [context.production.environment]
    REACT_APP_API_BASE_URL = "https://api.insureonline.com"
    REACT_APP_API_NAMESPACE = "v1"
    REACT_APP_VEHICLE_AUTOCOMPLETE_SEARCH = "true"
    NODE_ENV= "development"

[context.deploy-preview.environment]
  REACT_APP_API_BASE_URL = "https://api.insureonline.com"
  REACT_APP_API_NAMESPACE = "v1"
  REACT_APP_VEHICLE_AUTOCOMPLETE_SEARCH = "true"
  NODE_ENV = "development"


[context.branch-deploy]

[context.staging.environment]
